// Code generated by MockGen. DO NOT EDIT.
// Source: internal/app/repositories/refresh-tokens-repository.go
//
// Generated by this command:
//
//	mockgen -source=internal/app/repositories/refresh-tokens-repository.go -destination=tests/mocks/refresh-tokens-repository-mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	models "github.com/henrique998/go-ecommerce/internal/app/models"
	gomock "go.uber.org/mock/gomock"
)

// MockRefreshTokensRepository is a mock of RefreshTokensRepository interface.
type MockRefreshTokensRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRefreshTokensRepositoryMockRecorder
}

// MockRefreshTokensRepositoryMockRecorder is the mock recorder for MockRefreshTokensRepository.
type MockRefreshTokensRepositoryMockRecorder struct {
	mock *MockRefreshTokensRepository
}

// NewMockRefreshTokensRepository creates a new mock instance.
func NewMockRefreshTokensRepository(ctrl *gomock.Controller) *MockRefreshTokensRepository {
	mock := &MockRefreshTokensRepository{ctrl: ctrl}
	mock.recorder = &MockRefreshTokensRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRefreshTokensRepository) EXPECT() *MockRefreshTokensRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockRefreshTokensRepository) Create(rt models.RefreshToken) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", rt)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockRefreshTokensRepositoryMockRecorder) Create(rt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockRefreshTokensRepository)(nil).Create), rt)
}

// Delete mocks base method.
func (m *MockRefreshTokensRepository) Delete(val string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", val)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockRefreshTokensRepositoryMockRecorder) Delete(val any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockRefreshTokensRepository)(nil).Delete), val)
}

// FindByValue mocks base method.
func (m *MockRefreshTokensRepository) FindByValue(val string) models.RefreshToken {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByValue", val)
	ret0, _ := ret[0].(models.RefreshToken)
	return ret0
}

// FindByValue indicates an expected call of FindByValue.
func (mr *MockRefreshTokensRepositoryMockRecorder) FindByValue(val any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByValue", reflect.TypeOf((*MockRefreshTokensRepository)(nil).FindByValue), val)
}
