// Code generated by MockGen. DO NOT EDIT.
// Source: internal/app/services/account-services.go
//
// Generated by this command:
//
//	mockgen -source=internal/app/services/account-services.go -destination=tests/services-mocks/create-account-service-mock.go -package=servicesmocks
//

// Package servicesmocks is a generated GoMock package.
package servicesmocks

import (
	reflect "reflect"

	errors "github.com/henrique998/go-ecommerce/internal/app/errors"
	requests "github.com/henrique998/go-ecommerce/internal/app/requests"
	gomock "go.uber.org/mock/gomock"
)

// MockCreateAccountService is a mock of CreateAccountService interface.
type MockCreateAccountService struct {
	ctrl     *gomock.Controller
	recorder *MockCreateAccountServiceMockRecorder
}

// MockCreateAccountServiceMockRecorder is the mock recorder for MockCreateAccountService.
type MockCreateAccountServiceMockRecorder struct {
	mock *MockCreateAccountService
}

// NewMockCreateAccountService creates a new mock instance.
func NewMockCreateAccountService(ctrl *gomock.Controller) *MockCreateAccountService {
	mock := &MockCreateAccountService{ctrl: ctrl}
	mock.recorder = &MockCreateAccountServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCreateAccountService) EXPECT() *MockCreateAccountServiceMockRecorder {
	return m.recorder
}

// Execute mocks base method.
func (m *MockCreateAccountService) Execute(req requests.CreateAccountRequest) errors.AppErr {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Execute", req)
	ret0, _ := ret[0].(errors.AppErr)
	return ret0
}

// Execute indicates an expected call of Execute.
func (mr *MockCreateAccountServiceMockRecorder) Execute(req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockCreateAccountService)(nil).Execute), req)
}
